version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    networks:
      - hustlerfundserver_default
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
    depends_on:
      - zookeeper

    networks:
      - hustlerfundserver_default

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - hustlerfundserver_default
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - hustlerfundserver_default


networks:
  hustlerfundserver_default:

volumes:
  mongo_data:


