spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/hustlersFundDatabase
  kafka:
   consumer:
    bootstrap-servers: "kafka:29092"
    auto-offset-reset: earliest
    properties:
        retention.ms:



